const Map<String, String> ru = {
  "Next": "Следующий",
  "Skip": "Пропустить",
  "Lets Get Started": "Давайте начнем",
  "Tittle One": "Заголовок один",
  "Tittle Two": "Заголовок два",
  "Tittle Three": "Заголовок три",
  "Error": "Ошибка",
  "Ops! Something Went Wrong": "Ой! Что-то пошло не так",
  "Please check your internet connection\nand try again": "Пожалуйста, проверьте свое интернет-соединение\nи попробуйте снова",
  "Retry": "Повторить",
  "Confirmation Code": "Код подтверждения",
  "Enter the confirmation code we sent to": "Введите код подтверждения, который мы отправили на",
  "Didn’t receive the code? ": "Не получили код?",
  "Resend": "Отправить снова",
  "Submit": "Отправить",
  "Cancel": "Отменить",
  "Forget Password": "Забыли пароль",
  "Please fill email or phone number and \nwe'll send you a link to get back into your\naccount.":
      "Пожалуйста, введите адрес электронной почты или номер телефона,\nи мы отправим вам ссылку для восстановления доступа\nк вашей учетной записи.",
  "Email / Phone Number": "Электронная почта / Номер телефона",
  "Email Sent": "Письмо отправлено",
  "We sent an email to ": "Мы отправили письмо на",
  "with a link to get back into your account.": "с ссылкой для восстановления доступа к вашей учетной записи.",
  "Login to Your Account": "Войти в свою учетную запись",
  "Remember me": "Запомнить меня",
  "Login": "Войти",
  "Forget Password ?": "Забыли пароль?",
  "Or login with": "Или войти с помощью",
  "Don’t have an accoun’t ? ": "Нет учетной записи?",
  "Register": "Зарегистрироваться",
  "You are ready to go!": "Вы готовы!",
  "Congratulation, any interesting topics\nwill be shortly in your hands.": "Поздравляем, любые интересные темы\nскоро будут у вас под рукой.",
  "Finish": "Завершить",
  "Personalize Suggestion": "Персонализированные предложения",
  "Choose ": "Выберите",
  "min. 3 topic ": "мин. 3 темы",
  "you like, we will give": "которые вам нравятся, мы предложим",
  "you more often that relate to it.": "чаще соответствующие темы.",
  "Search Categories": "Поиск категорий",
  "Art": "Искусство",
  "Business": "Бизнес",
  "Comedy": "Комедия",
  "Culture": "Культура",
  "Education": "Образование",
  "News": "Новости",
  "Philosophy": "Философия",
  "Psychology": "Психология",
  "Technology": "Технологии",
  "Travel": "Путешествия",
  "topics Selected": "Темы выбраны",
  "Date of Birth": "Дата рождения",
  "By signing up, you agree to our ": "Регистрируясь, вы соглашаетесь с нашими",
  "Terms  ": "Условиями ",
  "Data Policy ": "Политикой обработки данных",
  "and ": "и",
  "Cookies Policy.": "Политикой использования файлов cookie.",
  "Welcome !": "Добро пожаловать!",
  "Find what you are looking for": "Найдите то, что вы ищете",
  "By personalize your account, we can help you to find what you like.":
      "Персонализируя вашу учетную запись, мы можем помочь вам найти то, что вам нравится.",
  "Personalize Your Account": "Персонализируйте свою учетную запись",
  "Select a language": "Выберите язык"
};
