const Map<String, String> uz = {
  "Next": "Keyingi",
  "Skip": "Otkazish",
  "Lets Get Started": "Keling, boshlaymiz",
  "Tittle One": "Birinchi sarlavha",
  "Tittle Two": "Ikkinchi sarlavha",
  "Tittle Three": "Uchinchi sarlavha",
  "Error": "Xato",
  "Ops! Something Went Wrong": "Of! Nimadir xato ketdi",
  "Please check your internet connection\nand try again": "Internet ulanishingizni tekshiring\va qayta urinib ko'ring",
  "Retry": "Qayta urinish",
  "Confirmation Code": "Tasdiqlash kodi",
  "Enter the confirmation code we sent to": "Enter the confirmation code we sent to",
  "Didn’t receive the code? ": "Kodni olmadingizmi?",
  "Resend": "Qayta yuborish",
  "Submit": "Yuborish",
  "Cancel": "Bekor qilish",
  "Forget Password": "Parolni unutish",
  "Please fill email or phone number and \nwe'll send you a link to get back into your\naccount.":
      "Iltimos, elektron pochta manzili yoki telefon raqamini toʻldiring, \nbiz sizga\nhisobingizga qaytish uchun havola yuboramiz.",
  "Email / Phone Number": "Elektron pochta / Telefon raqami",
  "Email Sent": "Elektron pochta yuborildi",
  "We sent an email to ": "Biz elektron pochta manziliga xat yubordik",
  "with a link to get back into your account.": "Hisobingizga qaytish uchun havola bilan.",
  "Login to Your Account": "Hisobingizga kiring",
  "Remember me": "Meni eslaysizmi",
  "Login": "Tizimga kirish",
  "Forget Password ?": "Parolni unutdingizmi?",
  "Or login with": "Yoki kiring",
  "Don’t have an accoun’t ? ": "Hisobingiz yo'qmi?",
  "Register": "Ro'yxatdan o'tish",
  "You are ready to go!": "Siz ketishga tayyorsiz!",
  "Congratulation, any interesting topics\nwill be shortly in your hands.":
      "Tabriklaymiz, har qanday qiziqarli mavzular\tez orada sizning qo'lingizda bo'ladi.",
  "Finish": "Tugatish",
  "Personalize Suggestion": "Taklifni shaxsiylashtirish",
  "Choose ": "Tanlash ",
  "min. 3 topic ": "kamida 3 ta mavzu ",
  "you like, we will give": "Sizga yoqadi,biz beramiz ",
  "you more often that relate to it.": "siz ko'pincha bu bilan bog'liqsiz.",
  "Search Categories": "Kategoriyalarni qidirish",
  "Art": "San'at",
  "Business": "Biznes",
  "Comedy": "Komediya",
  "Culture": "Madaniyat",
  "Education": "Ta'lim",
  "News": "Yangiliklar",
  "Philosophy": "Falsafa",
  "Psychology": "Psixologiya",
  "Technology": "Texnologiya",
  "Travel": "Sayohat",
  "topics Selected": "Mavzular tanlangan",
  "Date of Birth": "Tug'ilgan kuni",
  "By signing up, you agree to our ": "Ro'yxatdan o'tish orqali siz bizning roziligimiz",
  "Terms  ": "Shartlar ",
  "Data Policy ": "Ma'lumotlar siyosati ",
  "and ": "va ",
  "Cookies Policy.": "Cookie siyosati.",
  "Welcome !": "Xush kelibsiz !",
  "Find what you are looking for": "Izlaganingizni toping",
  "By personalize your account, we can help you to find what you like.":
      "Hisobingizni shaxsiylashtirish orqali biz sizga o'zingiz yoqtirgan narsani topishga yordam beramiz.",
  "Personalize Your Account": "Hisobingizni shaxsiylashtirish",
};
